name: Main workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: npm install -g yarn esy

      - name: Install node packages
        run: yarn install --frozen-lockfile

      - name: Install and build ocaml packages
        run: esy

      - name: Cleanup everything
        run: yarn clean

      - name: Extracting to OCaml
        run: |
          cd ocaml
          esy coqc ./coq/*.v

      - name: Compiling OCaml to JavaScript
        run: yarn build
